### PR TITLE
Created empty repository

### PR DESCRIPTION
**Pull request by ikaur1718**
Created empty repository with a component rendered, which displays Hello World!

### CODE REVIEW

**Comment by ikaur1718** [comment]
@kennisilverio Please review my changes? Let me know if they are ready to be pushed.

**Comment by ikaur1718** [comment]
@benmangold @jsangiolo92 @: Ready to push to master, with initial repo displaying hello world!

**Comment by jsangiolo92** [comment]
Looks good to me!

**Comment by benmangold** [comment]
looks good to me too!  feel free to merge

**Pull request merged**
